#!/usr/bin/env python3


def ranking_list(sorted_hotels):
    #sorted_hotels = sorted(hotels_list, key=lambda tup: tup[0])
    sorted_hotels_dict = {}
    for t in sorted_hotels:
        if t[0] in sorted_hotels_dict:
            sorted_hotels_dict[t[0]] = int(sorted_hotels_dict[t[0]]) + int(t[1])
        else:
            sorted_hotels_dict[t[0]] = t[1]

    for key,value in sorted_hotels_dict.items():
        print(key,value)
    

if __name__ == '__main__':

    N = int(input())
    hotels_list = []
    for i in range(0, N):
        i = input()
        hotels_list.append(i.split())
    ranking_list(hotels_list)
