#!/usr/bin/env python3

def merge(intervals):
    sorted_intervals = sorted(intervals, key=lambda tup: tup[0])
    merged = []
    for higher in sorted_intervals:
        if not merged:
            merged.append(higher)
        else:
            lower = merged[-1]
            if higher[0] <= lower[1]:
                upper_bound = max(lower[1], higher[1])
                merged[-1] = (lower[0], upper_bound)
            else:
                merged.append(higher)
    return merged

if __name__ == '__main__':

    N = int(input())
    numbers_list = []

    for i in range(0, N):
        i = input()
        numbers_list.append(i.split())

    result = merge(numbers_list)
    lengthofList = len(result)
    print (lengthofList)
    for printlist in result:
        print (printlist[0], printlist[1])
