#!/usr/bin/env bash

# Environment variables

export SED=`which sed`
export PWD=`which pwd`
export CURRENT_DIR=`${PWD}`
export FILENAME='./test'
export GREP=`which grep`
export UNIQ=`which uniq`
export GREP=`which grep`
export AWK=`which awk`
export SORT=`which sort`
export HEAD=`which head`

"${GREP}" -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}" ./test.txt | "${UNIQ}" -c | "${AWK}" '{print $2 " " $1}' | "${SORT}" -k2| "${HEAD}" -n 10   
